# Generated by Django 5.1.5 on 2025-02-12 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDFDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_pdf', models.FileField(upload_to='original_pdfs/')),
                ('signed_pdf', models.FileField(blank=True, null=True, upload_to='signed_pdfs/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('signature_placeholder_found', models.BooleanField(default=False)),
            ],
        ),
    ]
